version: '2.2'

services:
    php:
        container_name: container_php
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${LARAVEL_APP_PATH}:/var/www/laravel
            - ./logs/laravel:/var/www/laravel/var/log
        links:
            - mysql
    nginx:
        container_name: container_nginx
        build:
            context: nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
                SERVER_NAME: ${SERVER_NAME}
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    mysql:
        container_name: container_mysql
        image: mysql
        volumes:
            - ./.data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
